using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace NcpAdminBlazor.SourceGenerators
{
    [Generator]
    public class RepositoryGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(ctx => 
                ctx.AddSource("DebugInit.g.cs", SourceText.From($"// Initialized at {DateTime.Now}", Encoding.UTF8)));

            var compilationProvider = context.CompilationProvider;

            context.RegisterSourceOutput(compilationProvider, (spc, compilation) => Execute(spc, compilation));
        }

        private static void Execute(SourceProductionContext context, Compilation compilation)
        {
            context.AddSource("GeneratorTest.g.cs", SourceText.From($"// Compilation assembly: {compilation.AssemblyName}", Encoding.UTF8));

            var iAggregateRootSymbol = compilation.GetTypeByMetadataName("NetCorePal.Extensions.Domain.IAggregateRoot");
            if (iAggregateRootSymbol == null)
            {
                foreach (var refAssembly in compilation.SourceModule.ReferencedAssemblySymbols)
                {
                    iAggregateRootSymbol = refAssembly.GetTypeByMetadataName("NetCorePal.Extensions.Domain.IAggregateRoot");
                    if (iAggregateRootSymbol != null) break;
                }
            }

            if (iAggregateRootSymbol == null)
            {
                context.AddSource("Error.g.cs", SourceText.From("// IAggregateRoot not found", Encoding.UTF8));
                return;
            }

            var domainAssembly = compilation.SourceModule.ReferencedAssemblySymbols
                .FirstOrDefault(a => a.Name == "NcpAdminBlazor.Domain");

            if (domainAssembly == null)
            {
                if (compilation.AssemblyName == "NcpAdminBlazor.Domain")
                {
                    domainAssembly = compilation.Assembly;
                }
                else
                {
                    context.AddSource("Error_NoDomain.g.cs", SourceText.From($"// NcpAdminBlazor.Domain not found. Referenced: {string.Join(", ", compilation.SourceModule.ReferencedAssemblySymbols.Select(a => a.Name))}", Encoding.UTF8));
                    return;
                }
            }

            var entities = new List<EntityInfo>();
            VisitNamespace(domainAssembly.GlobalNamespace, iAggregateRootSymbol, entities);

            foreach (var entity in entities)
            {
                GenerateCode(context, entity);
            }
        }

        private static void VisitNamespace(INamespaceSymbol namespaceSymbol, INamedTypeSymbol iAggregateRootSymbol, List<EntityInfo> entities)
        {
            foreach (var member in namespaceSymbol.GetMembers())
            {
                if (member is INamespaceSymbol ns)
                {
                    VisitNamespace(ns, iAggregateRootSymbol, entities);
                }
                else if (member is INamedTypeSymbol type)
                {
                    if (type.TypeKind == TypeKind.Class && !type.IsAbstract && ImplementsInterface(type, iAggregateRootSymbol))
                    {
                        var idType = GetIdType(type);
                        if (idType != null)
                        {
                            entities.Add(new EntityInfo(type.Name, type.ContainingNamespace.ToDisplayString(), idType));
                        }
                    }
                }
            }
        }

        private static bool ImplementsInterface(INamedTypeSymbol type, INamedTypeSymbol interfaceSymbol)
        {
            return type.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, interfaceSymbol));
        }

        private static string? GetIdType(INamedTypeSymbol type)
        {
            var baseType = type.BaseType;
            while (baseType != null)
            {
                if (baseType.Name == "Entity" && baseType.TypeArguments.Length == 1)
                {
                    return baseType.TypeArguments[0].ToDisplayString();
                }
                baseType = baseType.BaseType;
            }
            return null;
        }

        private static void GenerateCode(SourceProductionContext context, EntityInfo info)
        {
            var entityName = info.Name;
            var entityNamespace = info.Namespace;
            var idType = info.IdType;
            var pluralEntityName = Pluralize(entityName);

            var interfaceCode = $@"// <auto-generated/>
using NetCorePal.Extensions.Domain;
using {entityNamespace};

namespace NcpAdminBlazor.Infrastructure.Repositories
{{
    public partial interface I{entityName}Repository : IRepository<{entityName}, {idType}>
    {{
    }}
}}";
            context.AddSource($"I{entityName}Repository.g.cs", SourceText.From(interfaceCode, Encoding.UTF8));

            var implementationCode = $@"// <auto-generated/>
using NetCorePal.Extensions.Repository.EntityFrameworkCore;
using NcpAdminBlazor.Infrastructure;
using {entityNamespace};

namespace NcpAdminBlazor.Infrastructure.Repositories
{{
    public partial class {entityName}Repository : RepositoryBase<{entityName}, {idType}, ApplicationDbContext>, I{entityName}Repository
    {{
        public {entityName}Repository(ApplicationDbContext context) : base(context)
        {{
        }}
    }}
}}";
            context.AddSource($"{entityName}Repository.g.cs", SourceText.From(implementationCode, Encoding.UTF8));

            var dbSetCode = $@"// <auto-generated/>
using Microsoft.EntityFrameworkCore;
using {entityNamespace};

namespace NcpAdminBlazor.Infrastructure
{{
    public partial class ApplicationDbContext
    {{
        public DbSet<{entityName}> {pluralEntityName} => Set<{entityName}>();
    }}
}}";
            context.AddSource($"ApplicationDbContext.{entityName}.g.cs", SourceText.From(dbSetCode, Encoding.UTF8));
        }

        private static string Pluralize(string name)
        {
            if (name.EndsWith("y"))
            {
                return name.Substring(0, name.Length - 1) + "ies";
            }
            if (name.EndsWith("s"))
            {
                return name + "es";
            }
            return name + "s";
        }
    }

    public sealed class EntityInfo : IEquatable<EntityInfo>
    {
        public string Name { get; }
        public string Namespace { get; }
        public string IdType { get; }

        public EntityInfo(string name, string ns, string idType)
        {
            Name = name;
            Namespace = ns;
            IdType = idType;
        }

        public bool Equals(EntityInfo? other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;
            return Name == other.Name && Namespace == other.Namespace && IdType == other.IdType;
        }

        public override bool Equals(object? obj)
        {
            return Equals(obj as EntityInfo);
        }

        public override int GetHashCode()
        {
            int hashCode = 17;
            hashCode = hashCode * 23 + Name.GetHashCode();
            hashCode = hashCode * 23 + Namespace.GetHashCode();
            hashCode = hashCode * 23 + IdType.GetHashCode();
            return hashCode;
        }
    }
}
