// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace CleanAdmin.Web.Client.ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CleanAdminApiServiceApplicationQueriesUsersUserInfoDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The phone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Phone { get; set; }
#nullable restore
#else
        public string Phone { get; set; }
#endif
        /// <summary>The realName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RealName { get; set; }
#nullable restore
#else
        public string RealName { get; set; }
#endif
        /// <summary>The roles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::CleanAdmin.Web.Client.ApiSdk.Models.CleanAdminApiServiceApplicationQueriesUsersUserRoleSummaryDto>? Roles { get; set; }
#nullable restore
#else
        public List<global::CleanAdmin.Web.Client.ApiSdk.Models.CleanAdminApiServiceApplicationQueriesUsersUserRoleSummaryDto> Roles { get; set; }
#endif
        /// <summary>The username property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Username { get; set; }
#nullable restore
#else
        public string Username { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::CleanAdmin.Web.Client.ApiSdk.Models.CleanAdminApiServiceApplicationQueriesUsersUserInfoDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::CleanAdmin.Web.Client.ApiSdk.Models.CleanAdminApiServiceApplicationQueriesUsersUserInfoDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::CleanAdmin.Web.Client.ApiSdk.Models.CleanAdminApiServiceApplicationQueriesUsersUserInfoDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "email", n => { Email = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "phone", n => { Phone = n.GetStringValue(); } },
                { "realName", n => { RealName = n.GetStringValue(); } },
                { "roles", n => { Roles = n.GetCollectionOfObjectValues<global::CleanAdmin.Web.Client.ApiSdk.Models.CleanAdminApiServiceApplicationQueriesUsersUserRoleSummaryDto>(global::CleanAdmin.Web.Client.ApiSdk.Models.CleanAdminApiServiceApplicationQueriesUsersUserRoleSummaryDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "username", n => { Username = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("phone", Phone);
            writer.WriteStringValue("realName", RealName);
            writer.WriteCollectionOfObjectValues<global::CleanAdmin.Web.Client.ApiSdk.Models.CleanAdminApiServiceApplicationQueriesUsersUserRoleSummaryDto>("roles", Roles);
            writer.WriteStringValue("username", Username);
        }
    }
}
#pragma warning restore CS0618
