// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace CleanAdmin.Web.Client.ApiSdk.Models
{
    /// <summary>菜单状态枚举</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CleanAdminDomainAggregatesModelMenuAggregateMenuStatus
    {
        [EnumMember(Value = "Enabled")]
        #pragma warning disable CS1591
        Enabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "Disabled")]
        #pragma warning disable CS1591
        Disabled,
        #pragma warning restore CS1591
    }
}
