// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace CleanAdmin.Web.Client.ApiSdk.Models
{
    /// <summary>
    /// 更新菜单请求DTO
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CleanAdminApiServiceEndpointsMenusUpdateMenuRequest : IParsable
    {
        /// <summary>The componentPath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ComponentPath { get; set; }
#nullable restore
#else
        public string ComponentPath { get; set; }
#endif
        /// <summary>The icon property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Icon { get; set; }
#nullable restore
#else
        public string Icon { get; set; }
#endif
        /// <summary>The menuName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MenuName { get; set; }
#nullable restore
#else
        public string MenuName { get; set; }
#endif
        /// <summary>The permissionCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PermissionCode { get; set; }
#nullable restore
#else
        public string PermissionCode { get; set; }
#endif
        /// <summary>The routePath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RoutePath { get; set; }
#nullable restore
#else
        public string RoutePath { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::CleanAdmin.Web.Client.ApiSdk.Models.CleanAdminApiServiceEndpointsMenusUpdateMenuRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::CleanAdmin.Web.Client.ApiSdk.Models.CleanAdminApiServiceEndpointsMenusUpdateMenuRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::CleanAdmin.Web.Client.ApiSdk.Models.CleanAdminApiServiceEndpointsMenusUpdateMenuRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "componentPath", n => { ComponentPath = n.GetStringValue(); } },
                { "icon", n => { Icon = n.GetStringValue(); } },
                { "menuName", n => { MenuName = n.GetStringValue(); } },
                { "permissionCode", n => { PermissionCode = n.GetStringValue(); } },
                { "routePath", n => { RoutePath = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("componentPath", ComponentPath);
            writer.WriteStringValue("icon", Icon);
            writer.WriteStringValue("menuName", MenuName);
            writer.WriteStringValue("permissionCode", PermissionCode);
            writer.WriteStringValue("routePath", RoutePath);
        }
    }
}
#pragma warning restore CS0618
