// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace CleanAdmin.Web.Client.ApiSdk.Models
{
    /// <summary>菜单类型枚举</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CleanAdminDomainAggregatesModelMenuAggregateMenuType
    {
        [EnumMember(Value = "Directory")]
        #pragma warning disable CS1591
        Directory,
        #pragma warning restore CS1591
        [EnumMember(Value = "Menu")]
        #pragma warning disable CS1591
        Menu,
        #pragma warning restore CS1591
        [EnumMember(Value = "Button")]
        #pragma warning disable CS1591
        Button,
        #pragma warning restore CS1591
    }
}
