// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace CleanAdmin.Web.Client.ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CleanAdminApiServiceApplicationQueriesMenusMenuPermissionTreeNodeDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The children property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::CleanAdmin.Web.Client.ApiSdk.Models.CleanAdminApiServiceApplicationQueriesMenusMenuPermissionTreeNodeDto>? Children { get; set; }
#nullable restore
#else
        public List<global::CleanAdmin.Web.Client.ApiSdk.Models.CleanAdminApiServiceApplicationQueriesMenusMenuPermissionTreeNodeDto> Children { get; set; }
#endif
        /// <summary>The icon property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Icon { get; set; }
#nullable restore
#else
        public string Icon { get; set; }
#endif
        /// <summary>The menuId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MenuId { get; set; }
#nullable restore
#else
        public string MenuId { get; set; }
#endif
        /// <summary>The menuName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MenuName { get; set; }
#nullable restore
#else
        public string MenuName { get; set; }
#endif
        /// <summary>The permissionCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PermissionCode { get; set; }
#nullable restore
#else
        public string PermissionCode { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::CleanAdmin.Web.Client.ApiSdk.Models.CleanAdminApiServiceApplicationQueriesMenusMenuPermissionTreeNodeDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::CleanAdmin.Web.Client.ApiSdk.Models.CleanAdminApiServiceApplicationQueriesMenusMenuPermissionTreeNodeDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::CleanAdmin.Web.Client.ApiSdk.Models.CleanAdminApiServiceApplicationQueriesMenusMenuPermissionTreeNodeDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "children", n => { Children = n.GetCollectionOfObjectValues<global::CleanAdmin.Web.Client.ApiSdk.Models.CleanAdminApiServiceApplicationQueriesMenusMenuPermissionTreeNodeDto>(global::CleanAdmin.Web.Client.ApiSdk.Models.CleanAdminApiServiceApplicationQueriesMenusMenuPermissionTreeNodeDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "icon", n => { Icon = n.GetStringValue(); } },
                { "menuId", n => { MenuId = n.GetStringValue(); } },
                { "menuName", n => { MenuName = n.GetStringValue(); } },
                { "permissionCode", n => { PermissionCode = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::CleanAdmin.Web.Client.ApiSdk.Models.CleanAdminApiServiceApplicationQueriesMenusMenuPermissionTreeNodeDto>("children", Children);
            writer.WriteStringValue("icon", Icon);
            writer.WriteStringValue("menuId", MenuId);
            writer.WriteStringValue("menuName", MenuName);
            writer.WriteStringValue("permissionCode", PermissionCode);
        }
    }
}
#pragma warning restore CS0618
