// <auto-generated/>
#pragma warning disable CS0618
using CleanAdmin.Web.Client.ApiSdk.Api.User.Item.Delete;
using CleanAdmin.Web.Client.ApiSdk.Api.User.Item.Profile;
using CleanAdmin.Web.Client.ApiSdk.Api.User.Item.Update;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CleanAdmin.Web.Client.ApiSdk.Api.User.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\user\{userId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithUserItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The deletePath property</summary>
        public global::CleanAdmin.Web.Client.ApiSdk.Api.User.Item.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::CleanAdmin.Web.Client.ApiSdk.Api.User.Item.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The profile property</summary>
        public global::CleanAdmin.Web.Client.ApiSdk.Api.User.Item.Profile.ProfileRequestBuilder Profile
        {
            get => new global::CleanAdmin.Web.Client.ApiSdk.Api.User.Item.Profile.ProfileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The update property</summary>
        public global::CleanAdmin.Web.Client.ApiSdk.Api.User.Item.Update.UpdateRequestBuilder Update
        {
            get => new global::CleanAdmin.Web.Client.ApiSdk.Api.User.Item.Update.UpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CleanAdmin.Web.Client.ApiSdk.Api.User.Item.WithUserItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUserItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/user/{userId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CleanAdmin.Web.Client.ApiSdk.Api.User.Item.WithUserItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUserItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/user/{userId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
