// <auto-generated/>
#pragma warning disable CS0618
using CleanAdmin.Web.Client.ApiSdk.Api.Ai.Chat;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CleanAdmin.Web.Client.ApiSdk.Api.Ai
{
    /// <summary>
    /// Builds and executes requests for operations under \api\ai
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The chat property</summary>
        public global::CleanAdmin.Web.Client.ApiSdk.Api.Ai.Chat.ChatRequestBuilder Chat
        {
            get => new global::CleanAdmin.Web.Client.ApiSdk.Api.Ai.Chat.ChatRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CleanAdmin.Web.Client.ApiSdk.Api.Ai.AiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/ai", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CleanAdmin.Web.Client.ApiSdk.Api.Ai.AiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/ai", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
