// <auto-generated/>
#pragma warning disable CS0618
using CleanAdmin.Web.Client.ApiSdk.Api.Menus.Item.Hide;
using CleanAdmin.Web.Client.ApiSdk.Api.Menus.Item.Show;
using CleanAdmin.Web.Client.ApiSdk.Api.Menus.Item.SortOrder;
using CleanAdmin.Web.Client.ApiSdk.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace CleanAdmin.Web.Client.ApiSdk.Api.Menus.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\menus\{menuId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithMenuItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The hide property</summary>
        public global::CleanAdmin.Web.Client.ApiSdk.Api.Menus.Item.Hide.HideRequestBuilder Hide
        {
            get => new global::CleanAdmin.Web.Client.ApiSdk.Api.Menus.Item.Hide.HideRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The show property</summary>
        public global::CleanAdmin.Web.Client.ApiSdk.Api.Menus.Item.Show.ShowRequestBuilder Show
        {
            get => new global::CleanAdmin.Web.Client.ApiSdk.Api.Menus.Item.Show.ShowRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sortOrder property</summary>
        public global::CleanAdmin.Web.Client.ApiSdk.Api.Menus.Item.SortOrder.SortOrderRequestBuilder SortOrder
        {
            get => new global::CleanAdmin.Web.Client.ApiSdk.Api.Menus.Item.SortOrder.SortOrderRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CleanAdmin.Web.Client.ApiSdk.Api.Menus.Item.WithMenuItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithMenuItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/menus/{menuId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CleanAdmin.Web.Client.ApiSdk.Api.Menus.Item.WithMenuItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithMenuItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/menus/{menuId}", rawUrl)
        {
        }
        /// <summary>
        /// 删除一个菜单项（菜单下无子菜单时才能删除）
        /// </summary>
        /// <returns>A <see cref="global::CleanAdmin.Web.Client.ApiSdk.Models.NetCorePalExtensionsDtoResponseDataOfEmptyResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::CleanAdmin.Web.Client.ApiSdk.Models.FastEndpointsErrorResponse">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::CleanAdmin.Web.Client.ApiSdk.Models.NetCorePalExtensionsDtoResponseDataOfEmptyResponse?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::CleanAdmin.Web.Client.ApiSdk.Models.NetCorePalExtensionsDtoResponseDataOfEmptyResponse> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::CleanAdmin.Web.Client.ApiSdk.Models.FastEndpointsErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::CleanAdmin.Web.Client.ApiSdk.Models.NetCorePalExtensionsDtoResponseDataOfEmptyResponse>(requestInfo, global::CleanAdmin.Web.Client.ApiSdk.Models.NetCorePalExtensionsDtoResponseDataOfEmptyResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 根据菜单ID获取菜单详细信息
        /// </summary>
        /// <returns>A <see cref="global::CleanAdmin.Web.Client.ApiSdk.Models.NetCorePalExtensionsDtoResponseDataOfMenuInfoDto"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::CleanAdmin.Web.Client.ApiSdk.Models.FastEndpointsErrorResponse">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::CleanAdmin.Web.Client.ApiSdk.Models.NetCorePalExtensionsDtoResponseDataOfMenuInfoDto?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::CleanAdmin.Web.Client.ApiSdk.Models.NetCorePalExtensionsDtoResponseDataOfMenuInfoDto> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::CleanAdmin.Web.Client.ApiSdk.Models.FastEndpointsErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::CleanAdmin.Web.Client.ApiSdk.Models.NetCorePalExtensionsDtoResponseDataOfMenuInfoDto>(requestInfo, global::CleanAdmin.Web.Client.ApiSdk.Models.NetCorePalExtensionsDtoResponseDataOfMenuInfoDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 更新菜单的基本信息
        /// </summary>
        /// <returns>A <see cref="global::CleanAdmin.Web.Client.ApiSdk.Models.NetCorePalExtensionsDtoResponseDataOfEmptyResponse"/></returns>
        /// <param name="body">更新菜单请求DTO</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::CleanAdmin.Web.Client.ApiSdk.Models.FastEndpointsErrorResponse">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::CleanAdmin.Web.Client.ApiSdk.Models.NetCorePalExtensionsDtoResponseDataOfEmptyResponse?> PutAsync(global::CleanAdmin.Web.Client.ApiSdk.Models.CleanAdminApiServiceEndpointsMenusUpdateMenuRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::CleanAdmin.Web.Client.ApiSdk.Models.NetCorePalExtensionsDtoResponseDataOfEmptyResponse> PutAsync(global::CleanAdmin.Web.Client.ApiSdk.Models.CleanAdminApiServiceEndpointsMenusUpdateMenuRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::CleanAdmin.Web.Client.ApiSdk.Models.FastEndpointsErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::CleanAdmin.Web.Client.ApiSdk.Models.NetCorePalExtensionsDtoResponseDataOfEmptyResponse>(requestInfo, global::CleanAdmin.Web.Client.ApiSdk.Models.NetCorePalExtensionsDtoResponseDataOfEmptyResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 删除一个菜单项（菜单下无子菜单时才能删除）
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// 根据菜单ID获取菜单详细信息
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// 更新菜单的基本信息
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">更新菜单请求DTO</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::CleanAdmin.Web.Client.ApiSdk.Models.CleanAdminApiServiceEndpointsMenusUpdateMenuRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::CleanAdmin.Web.Client.ApiSdk.Models.CleanAdminApiServiceEndpointsMenusUpdateMenuRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::CleanAdmin.Web.Client.ApiSdk.Api.Menus.Item.WithMenuItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::CleanAdmin.Web.Client.ApiSdk.Api.Menus.Item.WithMenuItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::CleanAdmin.Web.Client.ApiSdk.Api.Menus.Item.WithMenuItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithMenuItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithMenuItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithMenuItemRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
