// <auto-generated/>
#pragma warning disable CS0618
using CleanAdmin.Web.Client.ApiSdk.Api.Ai;
using CleanAdmin.Web.Client.ApiSdk.Api.Auth;
using CleanAdmin.Web.Client.ApiSdk.Api.Menus;
using CleanAdmin.Web.Client.ApiSdk.Api.Roles;
using CleanAdmin.Web.Client.ApiSdk.Api.User;
using CleanAdmin.Web.Client.ApiSdk.Api.Users;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CleanAdmin.Web.Client.ApiSdk.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ai property</summary>
        public global::CleanAdmin.Web.Client.ApiSdk.Api.Ai.AiRequestBuilder Ai
        {
            get => new global::CleanAdmin.Web.Client.ApiSdk.Api.Ai.AiRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The auth property</summary>
        public global::CleanAdmin.Web.Client.ApiSdk.Api.Auth.AuthRequestBuilder Auth
        {
            get => new global::CleanAdmin.Web.Client.ApiSdk.Api.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The menus property</summary>
        public global::CleanAdmin.Web.Client.ApiSdk.Api.Menus.MenusRequestBuilder Menus
        {
            get => new global::CleanAdmin.Web.Client.ApiSdk.Api.Menus.MenusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The roles property</summary>
        public global::CleanAdmin.Web.Client.ApiSdk.Api.Roles.RolesRequestBuilder Roles
        {
            get => new global::CleanAdmin.Web.Client.ApiSdk.Api.Roles.RolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public global::CleanAdmin.Web.Client.ApiSdk.Api.User.UserRequestBuilder User
        {
            get => new global::CleanAdmin.Web.Client.ApiSdk.Api.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::CleanAdmin.Web.Client.ApiSdk.Api.Users.UsersRequestBuilder Users
        {
            get => new global::CleanAdmin.Web.Client.ApiSdk.Api.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CleanAdmin.Web.Client.ApiSdk.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CleanAdmin.Web.Client.ApiSdk.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
