// <auto-generated/>
#pragma warning disable CS0618
using CleanAdmin.Web.Client.ApiSdk.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace CleanAdmin.Web.Client.ApiSdk.Api.User.List
{
    /// <summary>
    /// Builds and executes requests for operations under \api\user\list
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::CleanAdmin.Web.Client.ApiSdk.Api.User.List.ListRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/user/list?countTotal={countTotal}&pageIndex={pageIndex}&pageSize={pageSize}{&email*,phone*,realName*,username*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CleanAdmin.Web.Client.ApiSdk.Api.User.List.ListRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/user/list?countTotal={countTotal}&pageIndex={pageIndex}&pageSize={pageSize}{&email*,phone*,realName*,username*}", rawUrl)
        {
        }
        /// <summary>
        /// 按条件分页查询用户
        /// </summary>
        /// <returns>A <see cref="global::CleanAdmin.Web.Client.ApiSdk.Models.NetCorePalExtensionsDtoResponseDataOfPagedDataOfUserListItemDto"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::CleanAdmin.Web.Client.ApiSdk.Models.FastEndpointsErrorResponse">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::CleanAdmin.Web.Client.ApiSdk.Models.NetCorePalExtensionsDtoResponseDataOfPagedDataOfUserListItemDto?> GetAsync(Action<RequestConfiguration<global::CleanAdmin.Web.Client.ApiSdk.Api.User.List.ListRequestBuilder.ListRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::CleanAdmin.Web.Client.ApiSdk.Models.NetCorePalExtensionsDtoResponseDataOfPagedDataOfUserListItemDto> GetAsync(Action<RequestConfiguration<global::CleanAdmin.Web.Client.ApiSdk.Api.User.List.ListRequestBuilder.ListRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::CleanAdmin.Web.Client.ApiSdk.Models.FastEndpointsErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::CleanAdmin.Web.Client.ApiSdk.Models.NetCorePalExtensionsDtoResponseDataOfPagedDataOfUserListItemDto>(requestInfo, global::CleanAdmin.Web.Client.ApiSdk.Models.NetCorePalExtensionsDtoResponseDataOfPagedDataOfUserListItemDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 按条件分页查询用户
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::CleanAdmin.Web.Client.ApiSdk.Api.User.List.ListRequestBuilder.ListRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::CleanAdmin.Web.Client.ApiSdk.Api.User.List.ListRequestBuilder.ListRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::CleanAdmin.Web.Client.ApiSdk.Api.User.List.ListRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::CleanAdmin.Web.Client.ApiSdk.Api.User.List.ListRequestBuilder WithUrl(string rawUrl)
        {
            return new global::CleanAdmin.Web.Client.ApiSdk.Api.User.List.ListRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// 按条件分页查询用户
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ListRequestBuilderGetQueryParameters 
        {
            [QueryParameter("countTotal")]
            public bool? CountTotal { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("email")]
            public string? Email { get; set; }
#nullable restore
#else
            [QueryParameter("email")]
            public string Email { get; set; }
#endif
            [QueryParameter("pageIndex")]
            public int? PageIndex { get; set; }
            [QueryParameter("pageSize")]
            public int? PageSize { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("phone")]
            public string? Phone { get; set; }
#nullable restore
#else
            [QueryParameter("phone")]
            public string Phone { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("realName")]
            public string? RealName { get; set; }
#nullable restore
#else
            [QueryParameter("realName")]
            public string RealName { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("username")]
            public string? Username { get; set; }
#nullable restore
#else
            [QueryParameter("username")]
            public string Username { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ListRequestBuilderGetRequestConfiguration : RequestConfiguration<global::CleanAdmin.Web.Client.ApiSdk.Api.User.List.ListRequestBuilder.ListRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
