// <auto-generated/>
#pragma warning disable CS0618
using CleanAdmin.Web.Client.ApiSdk.Api.Menu.CurrentUser;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CleanAdmin.Web.Client.ApiSdk.Api.Menu
{
    /// <summary>
    /// Builds and executes requests for operations under \api\menu
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MenuRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The currentUser property</summary>
        public global::CleanAdmin.Web.Client.ApiSdk.Api.Menu.CurrentUser.CurrentUserRequestBuilder CurrentUser
        {
            get => new global::CleanAdmin.Web.Client.ApiSdk.Api.Menu.CurrentUser.CurrentUserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CleanAdmin.Web.Client.ApiSdk.Api.Menu.MenuRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MenuRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/menu", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CleanAdmin.Web.Client.ApiSdk.Api.Menu.MenuRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MenuRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/menu", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
