// <auto-generated/>
#pragma warning disable CS0618
using CleanAdmin.Web.Client.ApiSdk.Api.Menus.Tree.All;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CleanAdmin.Web.Client.ApiSdk.Api.Menus.Tree
{
    /// <summary>
    /// Builds and executes requests for operations under \api\menus\tree
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TreeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The all property</summary>
        public global::CleanAdmin.Web.Client.ApiSdk.Api.Menus.Tree.All.AllRequestBuilder All
        {
            get => new global::CleanAdmin.Web.Client.ApiSdk.Api.Menus.Tree.All.AllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CleanAdmin.Web.Client.ApiSdk.Api.Menus.Tree.TreeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TreeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/menus/tree", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CleanAdmin.Web.Client.ApiSdk.Api.Menus.Tree.TreeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TreeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/menus/tree", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
