// <auto-generated/>
#pragma warning disable CS0618
using CleanAdmin.Web.Client.ApiSdk.Api.User.Item;
using CleanAdmin.Web.Client.ApiSdk.Api.User.List;
using CleanAdmin.Web.Client.ApiSdk.Api.User.Permissions;
using CleanAdmin.Web.Client.ApiSdk.Api.User.Profile;
using CleanAdmin.Web.Client.ApiSdk.Api.User.Roles;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CleanAdmin.Web.Client.ApiSdk.Api.User
{
    /// <summary>
    /// Builds and executes requests for operations under \api\user
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The list property</summary>
        public global::CleanAdmin.Web.Client.ApiSdk.Api.User.List.ListRequestBuilder List
        {
            get => new global::CleanAdmin.Web.Client.ApiSdk.Api.User.List.ListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The permissions property</summary>
        public global::CleanAdmin.Web.Client.ApiSdk.Api.User.Permissions.PermissionsRequestBuilder Permissions
        {
            get => new global::CleanAdmin.Web.Client.ApiSdk.Api.User.Permissions.PermissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The profile property</summary>
        public global::CleanAdmin.Web.Client.ApiSdk.Api.User.Profile.ProfileRequestBuilder Profile
        {
            get => new global::CleanAdmin.Web.Client.ApiSdk.Api.User.Profile.ProfileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The roles property</summary>
        public global::CleanAdmin.Web.Client.ApiSdk.Api.User.Roles.RolesRequestBuilder Roles
        {
            get => new global::CleanAdmin.Web.Client.ApiSdk.Api.User.Roles.RolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the CleanAdmin.Web.Client.ApiSdk.api.user.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::CleanAdmin.Web.Client.ApiSdk.Api.User.Item.WithUserItemRequestBuilder"/></returns>
        public global::CleanAdmin.Web.Client.ApiSdk.Api.User.Item.WithUserItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("userId", position);
                return new global::CleanAdmin.Web.Client.ApiSdk.Api.User.Item.WithUserItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CleanAdmin.Web.Client.ApiSdk.Api.User.UserRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/user", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CleanAdmin.Web.Client.ApiSdk.Api.User.UserRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/user", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
